name: Test Automiation Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'QA 차수 입력'

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: |
          ls
          echo "${{ github.event.inputs.name }}"
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: report.xml
        env:
          secrets: ${{ secrets.ACTION_SECRET }}

