name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: pwd
      - name: xcresulttool
        uses: kishikawakatsumi/xcresulttool@v1.7.1
        if: success() || failure() # always run even if the previous step fails
        with:
          path: ./report.xcresult
        env:
          secrets: ${{ secrets.ACTION_SECRET }}

